name: Bug Report | BUG 报告
description: File a bug report | 提交一个 BUG 报告
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description | BUG 描述
      description: A clear and concise description of the bug. 一个清晰而简洁的错误描述。
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot | 相关截图
      description: If applicable, add screenshots or a screen recording to help explain your problem. 如果适用，请添加截图或屏幕录制以帮助解释您的问题。
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce | 重现问题
      description: Steps to reproduce the problem (if applicable). 重现问题的步骤（如果适用）。
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: input
    id: obsi-version
    attributes:
      label: Obsidian Version | Obsidian 版本
      description: You can find the version in the *About* Tab of the settings. 你可以在设置的*关于*选项卡中找到版本。
      placeholder: 0.13.19
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of the plugin. 我更新到了插件的最新版本。
          required: true

