name: Feature request
description: Suggest an idea
title: "Feature Request: "
labels: [ "feature request" ]
body:
    -   type: textarea
        id: feature-requested
        attributes:
            label: Feature Requested
            description: A clear and concise description of the feature.
        validations:
            required: true
    -   type: textarea
        id: screenshot
        attributes:
            label: Relevant Screenshot
            description: If applicable, add screenshots or a screen recording to help explain the request.
    -   type: checkboxes
        id: checklist
        attributes:
            label: Checklist
            options:
                -   label: The feature would be useful to more users than just me.
                    required: true

